---
title: "Visualizing remote sensing data"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

1. trop_mean_filt.tif: mean tropomi column density in $mol*10^2/cm^2$ Feb 2018 to Jan 2019. Data at [ tropomi datahub](https://s5phub.copernicus.eu/dhus/#/home); [earth engine](https://code.earthengine.google.com/?scriptPath=Examples:Datasets/COPERNICUS_S5P_NRTI_L3_NO2#)
2. OMI_mean_filt: annual mean OMI measured column density in $mol/cm^2$, values out of range are filtered.
3. Rsp: remote sensing and Chem-GEOS model estimated surface concentration.(http://fizz.phys.dal.ca/~atmos/martin/?page_id=232)

```{r}
ipak <- function(pkg){
 
   new.pkg <- pkg[!(pkg %in% installed.packages()[, "Package"])]
   if (length(new.pkg)) 
    install.packages(new.pkg, dependencies = TRUE, repos = "https://cloud.r-project.org")
  sapply(pkg, require, character.only = TRUE)
}
package = c("raster", "stars")
ipak(package)

trop = read_stars("rasters/trop_mean_filt.tif")
trop
system.time(plot(trop))
trop = raster("rasters/trop_mean_filt.tif")
trop
system.time(plot(trop))

plot(read_stars("rasters/OMI_mean_filt.tif"))
 
plot(raster("rasters/OMI_mean_filt.tif"))
plot(read_stars("rasters/Rsp.tif"))
plot(raster("rasters/Rsp.tif")) 
```
 
